load("//build-support/buck:workspace_rules.bzl", "workspace_library", "workspace_test")

workspace_library(
    name = "wt_translations",
    crate = "wt_translations",
    package = "wt-translations",
    version = "0.17.0",
    deps = [
        "//crates/wows-core:wows_core",
        "//third-party/rust:rust-i18n",
        "//third-party/rust:toml",
    ],
)

workspace_test(
    name = "wt_translations_test",
    crate = "wt_translations",
    crate_root = "src/lib.rs",
    package = "wt-translations",
    version = "0.17.0",
    deps = [
        "//crates/wows-core:wows_core",
        "//third-party/rust:rust-i18n",
        "//third-party/rust:toml",
    ],
)
