//! Per-version consumable id -> name tables.
//!
//! Recovered by static analysis of the obfuscated consumable-constants module in
//! each shipped client build (the `ConsumablesTypes` id ordering combined with
//! `ConsumableNamesMap`). Keyed on friendly version (major.minor.patch): a replay
//! resolves to the latest layout whose version it `is_at_least`. Regenerate with
//! `scripts/extract_consumable_ids.py` then `scripts/gen_consumable_ids_rs.py`.
//!
//! @generated -- do not edit by hand.

use crate::data::Version;

const fn v(major: u32, minor: u32, patch: u32) -> Version {
    Version { major, minor, patch, build: 0 }
}

/// Consumable id -> name layouts, ascending by version. Each table is the full
/// id -> name map effective from that version until the next entry supersedes it.
pub static CONSUMABLE_ID_LAYOUTS: &[(Version, &[(i32, &str)])] = &[
    (v(0, 9, 1), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "torpedoBoosters"), (5, "artilleryBoosters"), (6, "hangarBoosters"), (7, "smokeGenerator"), (9, "regenCrew"), (10, "fighter"), (11, "sonar"), (12, "torpedoReloader"), (13, "rls"), (14, "trigger1"), (15, "trigger2"), (16, "trigger3"), (17, "trigger4"), (18, "trigger5"), (19, "trigger6"), (20, "invulnerable"), (21, "healForsage"), (22, "callFighters"), (23, "regenerateHealth"), (24, "subsSnorkel"), (25, "subsOxygenRegen"), (26, "subsWaveGunBoost"), (27, "subsFourthState")]),
    (v(0, 9, 5), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "torpedoBoosters"), (5, "artilleryBoosters"), (6, "hangarBoosters"), (7, "smokeGenerator"), (9, "regenCrew"), (10, "fighter"), (11, "sonar"), (12, "torpedoReloader"), (13, "rls"), (14, "trigger1"), (15, "trigger2"), (16, "trigger3"), (17, "trigger4"), (18, "trigger5"), (19, "trigger6"), (20, "invulnerable"), (21, "healForsage"), (22, "callFighters"), (23, "regenerateHealth"), (24, "subsOxygenRegen"), (25, "subsWaveGunBoost"), (26, "subsFourthState"), (27, "depthCharges")]),
    (v(0, 9, 9), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "torpedoBoosters"), (5, "artilleryBoosters"), (6, "hangarBoosters"), (7, "smokeGenerator"), (9, "regenCrew"), (10, "fighter"), (11, "sonar"), (12, "torpedoReloader"), (13, "rls"), (14, "trigger1"), (15, "trigger2"), (16, "trigger3"), (17, "trigger4"), (18, "trigger5"), (19, "trigger6"), (20, "invulnerable"), (21, "healForsage"), (22, "callFighters"), (23, "regenerateHealth"), (24, "subsOxygenRegen"), (25, "subsWaveGunBoost"), (26, "subsFourthState"), (27, "depthCharges"), (28, "Any"), (29, "All")]),
    (v(0, 9, 10), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "torpedoBoosters"), (5, "artilleryBoosters"), (6, "hangarBoosters"), (7, "smokeGenerator"), (9, "regenCrew"), (10, "fighter"), (11, "sonar"), (12, "torpedoReloader"), (13, "rls"), (14, "trigger1"), (15, "trigger2"), (16, "trigger3"), (17, "trigger4"), (18, "trigger5"), (19, "trigger6"), (20, "invulnerable"), (21, "healForsage"), (22, "callFighters"), (23, "regenerateHealth"), (24, "subsOxygenRegen"), (25, "subsWaveGunBoost"), (26, "subsFourthState"), (27, "depthCharges"), (28, "trigger7"), (29, "trigger8"), (30, "trigger9"), (31, "beffsShift"), (32, "circleWave"), (33, "Any"), (34, "All")]),
    (v(0, 10, 1), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "torpedoBoosters"), (5, "artilleryBoosters"), (6, "hangarBoosters"), (7, "smokeGenerator"), (9, "regenCrew"), (10, "fighter"), (11, "sonar"), (12, "torpedoReloader"), (13, "rls"), (14, "trigger1"), (15, "trigger2"), (16, "trigger3"), (17, "trigger4"), (18, "trigger5"), (19, "trigger6"), (20, "invulnerable"), (21, "healForsage"), (22, "callFighters"), (23, "regenerateHealth"), (24, "subsOxygenRegen"), (25, "subsWaveGunBoost"), (26, "subsFourthState"), (27, "depthCharges"), (28, "trigger7"), (29, "trigger8"), (30, "trigger9"), (31, "beffsShift"), (32, "circleWave"), (33, "goDeep"), (34, "Any"), (35, "All")]),
    (v(0, 10, 2), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "torpedoBoosters"), (5, "artilleryBoosters"), (6, "hangarBoosters"), (7, "smokeGenerator"), (9, "regenCrew"), (10, "fighter"), (11, "sonar"), (12, "torpedoReloader"), (13, "rls"), (14, "trigger1"), (15, "trigger2"), (16, "trigger3"), (17, "trigger4"), (18, "trigger5"), (19, "trigger6"), (20, "invulnerable"), (21, "healForsage"), (22, "callFighters"), (23, "regenerateHealth"), (24, "subsOxygenRegen"), (25, "subsWaveGunBoost"), (26, "subsFourthState"), (27, "depthCharges"), (28, "trigger7"), (29, "trigger8"), (30, "trigger9"), (31, "beffsShift"), (32, "circleWave"), (33, "goDeep"), (34, "weaponReloadBooster"), (35, "Any"), (36, "All")]),
    (v(0, 10, 7), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "torpedoBoosters"), (5, "artilleryBoosters"), (6, "hangarBoosters"), (7, "smokeGenerator"), (9, "regenCrew"), (10, "fighter"), (11, "sonar"), (12, "torpedoReloader"), (13, "rls"), (14, "trigger1"), (15, "trigger2"), (16, "trigger3"), (17, "trigger4"), (18, "trigger5"), (19, "trigger6"), (20, "invulnerable"), (21, "healForsage"), (22, "callFighters"), (23, "regenerateHealth"), (24, "subsOxygenRegen"), (25, "subsWaveGunBoost"), (26, "subsFourthState"), (27, "depthCharges"), (28, "trigger7"), (29, "trigger8"), (30, "trigger9"), (31, "beffsShift"), (32, "circleWave"), (33, "goDeep"), (34, "weaponReloadBooster"), (35, "hydrophone"), (36, "fastRudders"), (37, "subsEnergyFreeze"), (38, "Any"), (39, "All")]),
    (v(0, 10, 9), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "torpedoBoosters"), (5, "artilleryBoosters"), (6, "hangarBoosters"), (7, "smokeGenerator"), (9, "regenCrew"), (10, "fighter"), (11, "sonar"), (12, "torpedoReloader"), (13, "rls"), (14, "trigger1"), (15, "trigger2"), (16, "trigger3"), (17, "trigger4"), (18, "trigger5"), (19, "trigger6"), (20, "invulnerable"), (21, "healForsage"), (22, "callFighters"), (23, "regenerateHealth"), (24, "subsOxygenRegen"), (25, "subsWaveGunBoost"), (26, "subsFourthState"), (27, "depthCharges"), (28, "trigger7"), (29, "trigger8"), (30, "trigger9"), (31, "beffsShift"), (32, "circleWave"), (33, "goDeep"), (34, "weaponReloadBooster"), (35, "hydrophone"), (36, "fastRudders"), (37, "subsEnergyFreeze"), (38, "groupAuraBuff"), (39, "affectedBuffAura"), (40, "invisibilityExtraBuffConsumable"), (41, "Any"), (42, "All")]),
    (v(0, 11, 7), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "torpedoBoosters"), (5, "artilleryBoosters"), (6, "hangarBoosters"), (7, "smokeGenerator"), (9, "regenCrew"), (10, "fighter"), (11, "sonar"), (12, "torpedoReloader"), (13, "rls"), (14, "trigger1"), (15, "trigger2"), (16, "trigger3"), (17, "trigger4"), (18, "trigger5"), (19, "trigger6"), (20, "invulnerable"), (21, "healForsage"), (22, "callFighters"), (23, "regenerateHealth"), (24, "subsOxygenRegen"), (25, "subsWaveGunBoost"), (26, "subsFourthState"), (27, "depthCharges"), (28, "trigger7"), (29, "trigger8"), (30, "trigger9"), (31, "beffsShift"), (32, "circleWave"), (33, "goDeep"), (34, "weaponReloadBooster"), (35, "hydrophone"), (36, "fastRudders"), (37, "subsEnergyFreeze"), (38, "groupAuraBuff"), (39, "affectedBuffAura"), (40, "invisibilityExtraBuffConsumable"), (41, "submarineLocator"), (42, "Any"), (43, "All")]),
    (v(12, 6, 0), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "torpedoBoosters"), (5, "artilleryBoosters"), (6, "hangarBoosters"), (7, "smokeGenerator"), (9, "regenCrew"), (10, "fighter"), (11, "sonar"), (12, "torpedoReloader"), (13, "rls"), (14, "trigger1"), (15, "trigger2"), (16, "trigger3"), (17, "trigger4"), (18, "trigger5"), (19, "trigger6"), (20, "invulnerable"), (21, "healForsage"), (22, "callFighters"), (23, "regenerateHealth"), (24, "subsOxygenRegen"), (25, "subsWaveGunBoost"), (26, "subsFourthState"), (27, "depthCharges"), (28, "trigger7"), (29, "trigger8"), (30, "trigger9"), (31, "beffsShift"), (32, "circleWave"), (33, "goDeep"), (34, "weaponReloadBooster"), (35, "hydrophone"), (36, "fastRudders"), (37, "subsEnergyFreeze"), (38, "groupAuraBuff"), (39, "affectedBuffAura"), (40, "invisibilityExtraBuffConsumable"), (41, "submarineLocator"), (42, "planeSmokeGenerator"), (43, "planeMinefield"), (44, "Any"), (45, "All")]),
    (v(12, 10, 0), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "artilleryBoosters"), (5, "hangarBoosters"), (6, "smokeGenerator"), (8, "regenCrew"), (9, "fighter"), (10, "sonar"), (11, "torpedoReloader"), (12, "rls"), (13, "trigger1"), (14, "trigger2"), (15, "trigger3"), (16, "trigger4"), (17, "trigger5"), (18, "trigger6"), (19, "invulnerable"), (20, "healForsage"), (21, "callFighters"), (22, "regenerateHealth"), (23, "subsOxygenRegen"), (24, "subsWaveGunBoost"), (25, "subsFourthState"), (26, "depthCharges"), (27, "trigger7"), (28, "trigger8"), (29, "trigger9"), (30, "beffsShift"), (31, "circleWave"), (32, "goDeep"), (33, "weaponReloadBooster"), (34, "hydrophone"), (35, "fastRudders"), (36, "subsEnergyFreeze"), (37, "groupAuraBuff"), (38, "affectedBuffAura"), (39, "invisibilityExtraBuffConsumable"), (40, "submarineLocator"), (41, "planeSmokeGenerator"), (42, "planeMinefield"), (43, "Any"), (44, "All")]),
    (v(13, 2, 0), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "artilleryBoosters"), (5, "hangarBoosters"), (6, "smokeGenerator"), (8, "regenCrew"), (9, "fighter"), (10, "sonar"), (11, "torpedoReloader"), (12, "rls"), (13, "trigger1"), (14, "trigger2"), (15, "trigger3"), (16, "trigger4"), (17, "trigger5"), (18, "trigger6"), (19, "invulnerable"), (20, "healForsage"), (21, "callFighters"), (22, "regenerateHealth"), (23, "subsOxygenRegen"), (24, "subsWaveGunBoost"), (25, "subsFourthState"), (26, "depthCharges"), (27, "trigger7"), (28, "trigger8"), (29, "trigger9"), (30, "buffsShift"), (31, "circleWave"), (32, "goDeep"), (33, "weaponReloadBooster"), (34, "hydrophone"), (35, "fastRudders"), (36, "subsEnergyFreeze"), (37, "groupAuraBuff"), (38, "affectedBuffAura"), (39, "invisibilityExtraBuffConsumable"), (40, "submarineLocator"), (41, "planeSmokeGenerator"), (42, "planeMinefield"), (43, "minefield"), (44, "tacticalTrigger1"), (45, "tacticalTrigger2"), (46, "tacticalTrigger3"), (47, "tacticalTrigger4"), (48, "tacticalTrigger5"), (49, "tacticalTrigger6"), (50, "reconnaissanceSquad"), (51, "smokePlane"), (52, "Any"), (53, "All"), (54, "Special")]),
    (v(13, 4, 0), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "artilleryBoosters"), (5, "hangarBoosters"), (6, "smokeGenerator"), (8, "regenCrew"), (9, "fighter"), (10, "sonar"), (11, "torpedoReloader"), (12, "rls"), (13, "trigger1"), (14, "trigger2"), (15, "trigger3"), (16, "trigger4"), (17, "trigger5"), (18, "trigger6"), (19, "invulnerable"), (20, "healForsage"), (21, "callFighters"), (22, "regenerateHealth"), (23, "subsOxygenRegen"), (24, "subsWaveGunBoost"), (25, "subsFourthState"), (26, "depthCharges"), (27, "trigger7"), (28, "trigger8"), (29, "trigger9"), (30, "buff"), (31, "buffsShift"), (32, "circleWave"), (33, "goDeep"), (34, "weaponReloadBooster"), (35, "hydrophone"), (36, "fastRudders"), (37, "subsEnergyFreeze"), (38, "groupAuraBuff"), (39, "affectedBuffAura"), (40, "invisibilityExtraBuffConsumable"), (41, "submarineLocator"), (42, "planeSmokeGenerator"), (43, "planeMinefield"), (44, "minefield"), (45, "tacticalTrigger1"), (46, "tacticalTrigger2"), (47, "tacticalTrigger3"), (48, "tacticalTrigger4"), (49, "tacticalTrigger5"), (50, "tacticalTrigger6"), (51, "reconnaissanceSquad"), (52, "smokePlane"), (53, "tacticalBuff"), (54, "Any"), (55, "All"), (56, "Special")]),
    (v(14, 7, 1), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "artilleryBoosters"), (5, "hangarBoosters"), (6, "smokeGenerator"), (8, "regenCrew"), (9, "fighter"), (10, "sonar"), (11, "torpedoReloader"), (12, "rls"), (13, "trigger1"), (14, "trigger2"), (15, "trigger3"), (16, "trigger4"), (17, "trigger5"), (18, "trigger6"), (19, "invulnerable"), (20, "healForsage"), (21, "callFighters"), (22, "regenerateHealth"), (23, "subsOxygenRegen"), (24, "subsWaveGunBoost"), (25, "subsFourthState"), (26, "depthCharges"), (27, "trigger7"), (28, "trigger8"), (29, "trigger9"), (30, "buff"), (31, "buffsShift"), (32, "circleWave"), (33, "goDeep"), (34, "weaponReloadBooster"), (35, "hydrophone"), (36, "fastRudders"), (37, "subsEnergyFreeze"), (38, "groupAuraBuff"), (39, "affectedBuffAura"), (40, "invisibilityExtraBuffConsumable"), (41, "submarineLocator"), (42, "planeSmokeGenerator"), (43, "planeMinefield"), (44, "minefield"), (45, "tacticalTrigger1"), (46, "tacticalTrigger2"), (47, "tacticalTrigger3"), (48, "tacticalTrigger4"), (49, "tacticalTrigger5"), (50, "tacticalTrigger6"), (51, "reconnaissanceSquad"), (52, "smokePlane"), (53, "tacticalBuff"), (54, "planeTrigger1"), (55, "planeTrigger2"), (56, "planeTrigger3"), (57, "planeBuff"), (58, "Any"), (59, "All"), (60, "Special")]),
    (v(15, 2, 0), &[(0, "crashCrew"), (1, "scout"), (2, "airDefenseDisp"), (3, "speedBoosters"), (4, "artilleryBoosters"), (5, "hangarBoosters"), (6, "smokeGenerator"), (8, "regenCrew"), (9, "fighter"), (10, "sonar"), (11, "torpedoReloader"), (12, "rls"), (13, "trigger1"), (14, "trigger2"), (15, "trigger3"), (16, "trigger4"), (17, "trigger5"), (18, "trigger6"), (19, "invulnerable"), (20, "healForsage"), (21, "activeManeuvering"), (22, "callFighters"), (23, "regenerateHealth"), (24, "subsOxygenRegen"), (25, "subsWaveGunBoost"), (26, "subsFourthState"), (27, "depthCharges"), (28, "trigger7"), (29, "trigger8"), (30, "trigger9"), (31, "buff"), (32, "buffsShift"), (33, "circleWave"), (34, "goDeep"), (35, "weaponReloadBooster"), (36, "hydrophone"), (37, "fastRudders"), (38, "subsEnergyFreeze"), (39, "groupAuraBuff"), (40, "affectedBuffAura"), (41, "invisibilityExtraBuffConsumable"), (42, "submarineLocator"), (43, "planeSmokeGenerator"), (44, "planeMinefield"), (45, "minefield"), (46, "tacticalTrigger1"), (47, "tacticalTrigger2"), (48, "tacticalTrigger3"), (49, "tacticalTrigger4"), (50, "tacticalTrigger5"), (51, "tacticalTrigger6"), (52, "reconnaissanceSquad"), (53, "smokePlane"), (54, "tacticalBuff"), (55, "planeTrigger1"), (56, "planeTrigger2"), (57, "planeTrigger3"), (58, "planeBuff"), (59, "planeTacticalFighters"), (60, "Any"), (61, "All"), (62, "Special")]),
];

/// The consumable id -> name table effective for `version`: the latest layout
/// whose friendly version is <= `version`. Versions older than every known layout
/// floor to the earliest one (the closest available approximation).
pub fn consumable_ids_for_version(version: Version) -> Option<&'static [(i32, &'static str)]> {
    CONSUMABLE_ID_LAYOUTS
        .iter()
        .rev()
        .find(|(start, _)| version.is_at_least(start))
        .or_else(|| CONSUMABLE_ID_LAYOUTS.first())
        .map(|(_, table)| *table)
}
