import re
import struct


def murmurhash3_32(key, seed=0):
    key = key.encode("utf-8") if isinstance(key, str) else key
    length = len(key)
    nblocks = length // 4
    h1 = seed & 0xFFFFFFFF
    c1 = 0xCC9E2D51
    c2 = 0x1B873593
    for i in range(nblocks):
        k1 = struct.unpack_from("<I", key, i * 4)[0]
        k1 = (k1 * c1) & 0xFFFFFFFF
        k1 = ((k1 << 15) | (k1 >> 17)) & 0xFFFFFFFF
        k1 = (k1 * c2) & 0xFFFFFFFF
        h1 ^= k1
        h1 = ((h1 << 13) | (h1 >> 19)) & 0xFFFFFFFF
        h1 = (h1 * 5 + 0xE6546B64) & 0xFFFFFFFF
    tail = key[nblocks * 4 :]
    k1 = 0
    if len(tail) >= 3:
        k1 ^= tail[2] << 16
    if len(tail) >= 2:
        k1 ^= tail[1] << 8
    if len(tail) >= 1:
        k1 ^= tail[0]
        k1 = (k1 * c1) & 0xFFFFFFFF
        k1 = ((k1 << 15) | (k1 >> 17)) & 0xFFFFFFFF
        k1 = (k1 * c2) & 0xFFFFFFFF
        h1 ^= k1
    h1 ^= length
    h1 ^= h1 >> 16
    h1 = (h1 * 0x85EBCA6B) & 0xFFFFFFFF
    h1 ^= h1 >> 13
    h1 = (h1 * 0xC2B2AE35) & 0xFFFFFFFF
    h1 ^= h1 >> 16
    return h1


TARGET = {
    0x0F6CD1D5,
    0x1920351F,
    0x2430B8E8,
    0x415BB4C1,
    0x473590AF,
    0x4BF80D47,
    0x4C72E480,
    0x54A8F7F9,
    0x5BC23E80,
    0x621551F5,
    0x750CA416,
    0x985C860C,
    0x9FA99E8C,
    0xA23CBF8B,
    0xAE0EFD2D,
    0xBD0A648D,
    0xE37F571C,
}
INFO = {
    0x0F6CD1D5: "tex[0]",
    0x54A8F7F9: "tex[1]",
    0x1920351F: "tex[2]",
    0x4BF80D47: "tex[3]",
    0x9FA99E8C: "tex[4]",
    0xA23CBF8B: "bool[0]",
    0xE37F571C: "float[0]=0.0",
    0x2430B8E8: "float[1]=0.002",
    0x4C72E480: "float[2]=18.0",
    0x985C860C: "float[3]=0.3",
    0xBD0A648D: "float[4]=0.8",
    0x473590AF: "float[5]=0.5",
    0x5BC23E80: "vec4[0]=(0.5,0.7,0.1,0)",
    0x415BB4C1: "vec4[1]=(-0.5,1,0,1)",
    0x621551F5: "vec4[2]=(1,0.2,0,0)",
    0xAE0EFD2D: "vec4[3]=(10,6,8,4)",
    0x750CA416: "vec4[4]=(1,0,0,0)",
}

raw_names = [
    # Textures
    "diffuseMap",
    "normalMap",
    "specularMap",
    "heightMap",
    "blendMap",
    "overlayMap",
    "diffuseTexture",
    "normalTexture",
    "specularTexture",
    "heightTexture",
    "albedoMap",
    "albedoTexture",
    "metallicMap",
    "roughnessMap",
    "aoMap",
    "tilesMap",
    "tilesTexture",
    "tileAtlas",
    "tileMap",
    "tilesAlbedoMap",
    "tilesNormalMap",
    "tilesSpecularMap",
    "tilesHeightMap",
    "tilesAlbedo",
    "tilesNormal",
    "tilesSpecular",
    "tilesHeight",
    "tilesDiffuseMap",
    "tilesDiffuse",
    "overlayDiffuseMap",
    "overlayDiffuse",
    "overlayNormalMap",
    "overlaySpecularMap",
    "overlayHeightMap",
    "colorMap",
    "colorTexture",
    "detailMap",
    "detailTexture",
    "baseColorMap",
    "baseColorTexture",
    "emissiveMap",
    "emissiveTexture",
    "occlusionMap",
    "occlusionTexture",
    "glossMap",
    "glossTexture",
    "maskMap",
    "maskTexture",
    "splatMap",
    "splatTexture",
    "weightMap",
    "weightTexture",
    "blendTexture",
    "blendWeight",
    "layerMap",
    "layerTexture",
    "terrainMap",
    "terrainTexture",
    "environmentMap",
    "reflectionMap",
    "lightMap",
    "shadowMap",
    "displacementMap",
    "bumpMap",
    "opacityMap",
    "opacityTexture",
    "materialKindMap",
    "materialKindTexture",
    "macroNormalMap",
    "macroMap",
    "microNormalMap",
    "microDetailMap",
    "microDetailNormalMap",
    "globalMap",
    "globalNormalMap",
    "globalDiffuseMap",
    "compositeMap",
    "compositeTexture",
    "proceduralMap",
    "tileAlbedoMap",
    "tileNormalMap",
    "tileSpecularMap",
    "tileHeightMap",
    "tiledMap",
    "tiledTexture",
    "landTexture",
    "landMap",
    "groundMap",
    "groundTexture",
    "surfaceMap",
    "surfaceTexture",
    "terrainTilesAtlas",
    "terrainNormalsAtlas",
    "terrainBlendMap",
    "terrainHeightMap",
    "terrainSplatMap",
    "terrainOverlayMap",
    "tilesAtlas",
    "normalsAtlas",
    "heightsAtlas",
    "specularsAtlas",
    "atlasTexture",
    "atlasDiffuse",
    "atlasNormal",
    "atlasSpecular",
    "textureAtlas",
    "diffuseAtlas",
    "normalAtlas",
    "specularAtlas",
    "diffuseMap2",
    "normalMap2",
    "specularMap2",
    "diffuseMap3",
    "normalMap3",
    "specularMap3",
    "diffuseMap4",
    "normalMap4",
    "specularMap4",
    "tex0",
    "tex1",
    "tex2",
    "tex3",
    "tex4",
    "tex5",
    "tex6",
    "tex7",
    "texture0",
    "texture1",
    "texture2",
    "texture3",
    "map0",
    "map1",
    "map2",
    "map3",
    "map4",
    # Booleans
    "doubleSided",
    "alphaTest",
    "alphaBlend",
    "useAlpha",
    "useNormal",
    "useSpecular",
    "useHeight",
    "useOverlay",
    "useTiling",
    "useBlend",
    "useDetail",
    "useMacro",
    "wireframe",
    "castShadow",
    "receiveShadow",
    "dynamicLighting",
    "flipNormal",
    "flipV",
    "flipU",
    "transparent",
    "twoSided",
    "backFaceCull",
    "depthWrite",
    "depthTest",
    "alphaReference",
    "alphaCutoff",
    "useVertexColor",
    "useVertexAlpha",
    "fog",
    "fogEnabled",
    "useFog",
    "hasAlpha",
    "alphaTestEnable",
    # Floats
    "tilingFactor",
    "tileScale",
    "uvTiling",
    "uvScale",
    "blendFactor",
    "blendSharpness",
    "blendContrast",
    "normalStrength",
    "normalScale",
    "bumpScale",
    "heightScale",
    "heightFactor",
    "heightOffset",
    "specularPower",
    "specularStrength",
    "shininess",
    "glossiness",
    "roughness",
    "metallic",
    "metalness",
    "opacity",
    "alpha",
    "alphaRef",
    "alphaTestRef",
    "displacementScale",
    "displacementOffset",
    "detailScale",
    "detailTiling",
    "microScale",
    "macroScale",
    "macroTiling",
    "globalScale",
    "overlayScale",
    "overlayTiling",
    "overlayStrength",
    "diffuseScale",
    "colorScale",
    "brightness",
    "contrast",
    "saturation",
    "hue",
    "gamma",
    "tileSize",
    "tileRepeat",
    "texelDensity",
    "fresnel",
    "fresnelPower",
    "fresnelScale",
    "parallaxScale",
    "parallaxOffset",
    "parallaxDepth",
    "aoStrength",
    "aoScale",
    "emissiveStrength",
    "materialKind",
    "materialIndex",
    "layerCount",
    "blendMode",
    "renderOrder",
    "sortOrder",
    "fadeStart",
    "fadeEnd",
    "fadeDistance",
    # Vec4
    "tileIndices",
    "tileScales",
    "tileWeights",
    "tileParams",
    "layerConfig",
    "layerParams",
    "layerWeights",
    "layerIndices",
    "blendParams",
    "blendConfig",
    "blendWeights",
    "colorTint",
    "diffuseTint",
    "specularTint",
    "uvScaleOffset",
    "uvParams",
    "textureParams",
    "materialParams",
    "materialConfig",
    "renderParams",
    "fogParams",
    "shadowParams",
    "fadeParams",
    "lodParams",
    "detailParams",
    "overlayParams",
    "terrainParams",
    "heightParams",
    "normalParams",
    "specularParams",
    "layerScales",
    "layerTiling",
    "layerOffsets",
    "tileConfig",
    "tileMapping",
    "tileLayers",
    "splatWeights",
    "splatParams",
    "splatConfig",
    "blendColor",
    "blendTint",
    "tileUVScales",
    "tileIndices0",
    "tileIndices1",
    "overlayColor",
    "overlayTint",
    "tilingParams",
    "tilingConfig",
    "tilingScales",
    # Single word / short
    "diffuse",
    "normal",
    "specular",
    "height",
    "blend",
    "overlay",
    "albedo",
    "metallic",
    "roughness",
    "ao",
    "emissive",
    "occlusion",
    "gloss",
    "color",
    "diffuseColor",
    "specularColor",
    "emissiveColor",
    "ambientColor",
    "tintColor",
    "baseColor",
    "albedoColor",
    # BigWorld specific
    "selfIllumination",
    "selfIlluminationColour",
    "materialFresnel",
    "materialKindValue",
    "texAnimMatrix",
    "materialID",
    "specularColour",
    "diffuseColour",
    "ambientColour",
    "emissiveColour",
    "selfIlluminationColor",
    "specularFresnel",
    "reflectionTint",
    "glowStrength",
    "glowColor",
    "terrainScale",
    "terrainOffset",
    "tileBlend",
    "tileTransition",
    "blendDistance",
    "blendRange",
    "blendHeight",
    "slopeBlend",
    "slopeAngle",
    "slopeSharpness",
    "vegetationMask",
    "vegetationDensity",
    "tileUVScale",
    "tileUVOffset",
    # WoT/BigWorld known shader property names
    "g_useNormalPackDXT1",
    "g_specularMultiplier",
    "g_detailDensity",
    "g_detailFadeDistance",
    "g_textureTransform",
    "g_material",
    "g_useParallax",
    "g_parallaxParams",
    "g_diffuseColour",
    "g_materialColour",
    "g_fresnelExp",
    "g_fresnelCoef",
    # WoWs-specific names found from assets.bin string table
    "AHArray",
    "ODMap",
    "RNAOArray",
    "RNBMap",
    "g_metallic",
    "g_overlayDetail",
    "g_tilesScale",
    "sheen",
    "sheenRoughness",
    "sheenTint",
    "addSheenTintColor",
    "g_overlayDepth",
    "g_overlayOpacity",
    "g_tilesIndex",
    "sheenChannelMask",
]

names = set(raw_names)
extra = set()
for n in list(names):
    # camelCase -> snake_case
    snake = re.sub(r"(?<!^)(?=[A-Z])", "_", n).lower()
    if snake != n.lower():
        extra.add(snake)
    # Map/Texture/Tex suffix variations
    if n.endswith("Map"):
        extra.update([n[:-3] + "Texture", n[:-3] + "Tex", n[:-3]])
    elif n.endswith("Texture"):
        extra.update([n[:-7] + "Map", n[:-7] + "Tex", n[:-7]])

names.update(extra)

print(f"Testing {len(names)} candidates against {len(TARGET)} hashes")
found = {}
for n in sorted(names):
    h = murmurhash3_32(n)
    if h in TARGET:
        found[h] = n
        print(f"  MATCH: {n} -> 0x{h:08x} = {INFO.get(h, '?')}")

print(f"\n=== Summary: {len(found)}/{len(TARGET)} cracked ===")
for h in sorted(TARGET):
    name = found.get(h, "???")
    print(f"  0x{h:08x} {INFO.get(h, '?'):30s} = {name}")

remaining = TARGET - set(found.keys())
if remaining:
    print(f"\n{len(remaining)} hashes still uncracked:")
    for h in sorted(remaining):
        print(f"  0x{h:08x}  {INFO.get(h, '?')}")
