#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate the Rust skill-grid table from scripts/skill_grids.json.

skill_grids.json is the deduped modern (>=0.10) captain skill layout produced by
skill_grids_extract.py. This emits a static Rust module the toolkit compiles in,
so the build has no runtime/data dependency. Re-run after refreshing the JSON.

Usage (python 2 or 3):
  python scripts/gen_skill_grid_rs.py
"""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
JSON_IN = os.path.join(HERE, "skill_grids.json")
RS_OUT = os.path.join(ROOT, "crates", "wows-toolkit", "src", "replay", "renderer", "skill_grid_data.rs")

# JSON ship-type key -> Rust Layout field name.
SHIP_FIELDS = [
    ("AIRCARRIER", "air_carrier"),
    ("BATTLESHIP", "battleship"),
    ("CRUISER", "cruiser"),
    ("DESTROYER", "destroyer"),
    ("SUBMARINE", "submarine"),
    ("AUXILIARY", "auxiliary"),
]
GROUP_RS = {"ATTACK": "Attack", "DEFENCE": "Defence", "SUPPORT": "Support", "ACUMEN": "Acumen"}

HEADER = """\
//! GENERATED by scripts/gen_skill_grid_rs.py from scripts/skill_grids.json.
//! Do not edit by hand. Modern (>=0.10) captain skill grid layout, per build
//! threshold and ship species, reverse-engineered from the client's
//! SKILLS_BY_SHIP_TYPE table. Pre-0.10 builds carry tier+column in GameParams
//! instead and are not covered here. Regenerate after adding game versions.
#![allow(dead_code)]

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SkillGroup {
    Attack,
    Defence,
    Support,
    Acumen,
}

#[derive(Clone, Copy, Debug)]
pub struct GridSlot {
    /// Skill internal name (matches `CrewSkill::internal_name`).
    pub skill: &'static str,
    /// 0-based tier (row); point cost is `tier + 1`.
    pub tier: u8,
    /// 1-based column within the tier.
    pub column: u8,
    pub group: SkillGroup,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SkillSpecies {
    AirCarrier,
    Battleship,
    Cruiser,
    Destroyer,
    Submarine,
    Auxiliary,
}

struct Layout {
    min_build: u32,
    air_carrier: &'static [GridSlot],
    battleship: &'static [GridSlot],
    cruiser: &'static [GridSlot],
    destroyer: &'static [GridSlot],
    submarine: &'static [GridSlot],
    auxiliary: &'static [GridSlot],
}

impl Layout {
    fn species(&self, s: SkillSpecies) -> &'static [GridSlot] {
        match s {
            SkillSpecies::AirCarrier => self.air_carrier,
            SkillSpecies::Battleship => self.battleship,
            SkillSpecies::Cruiser => self.cruiser,
            SkillSpecies::Destroyer => self.destroyer,
            SkillSpecies::Submarine => self.submarine,
            SkillSpecies::Auxiliary => self.auxiliary,
        }
    }
}

/// Modern skill grid for `build` and `species`. Empty when `build` predates the
/// modern skill system. Picks the layout with the largest `min_build <= build`.
pub fn modern_grid(build: u32, species: SkillSpecies) -> &'static [GridSlot] {
    let mut chosen: Option<&Layout> = None;
    for layout in LAYOUTS {
        if layout.min_build <= build {
            chosen = Some(layout);
        } else {
            break;
        }
    }
    chosen.map(|l| l.species(species)).unwrap_or(&[])
}

"""


def slot_lit(s):
    return '        GridSlot { skill: "%s", tier: %d, column: %d, group: SkillGroup::%s },' % (
        s["skill"],
        s["tier"],
        s["column"],
        GROUP_RS[s["group"]],
    )


def main():
    data = json.load(io.open(JSON_IN, encoding="utf-8"))
    data.sort(key=lambda e: e["min_build"])

    out = io.StringIO()
    out.write(HEADER)
    out.write(u"static LAYOUTS: &[Layout] = &[\n")
    for entry in data:
        out.write(u"    // %s\n" % entry["version"])
        out.write(u"    Layout {\n")
        out.write(u"        min_build: %d,\n" % entry["min_build"])
        for json_key, field in SHIP_FIELDS:
            slots = entry["grid"].get(json_key, [])
            slots = sorted(slots, key=lambda s: (s["tier"], s["column"]))
            if not slots:
                out.write(u"        %s: &[],\n" % field)
                continue
            out.write(u"        %s: &[\n" % field)
            for s in slots:
                out.write(slot_lit(s) + u"\n")
            out.write(u"        ],\n")
        out.write(u"    },\n")
    out.write(u"];\n")

    with io.open(RS_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(out.getvalue())
    n_layouts = len(data)
    n_slots = sum(len(v) for e in data for v in e["grid"].values())
    print("wrote %s (%d layouts, %d slots)" % (RS_OUT, n_layouts, n_slots))


if __name__ == "__main__":
    main()
