#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate the Rust skill-grid table from scripts/skill_grids.json.

skill_grids.json is the deduped modern (>=0.10) captain skill layout produced by
skill_grids_extract.py. This emits a static Rust module the toolkit compiles in,
so the build has no runtime/data dependency. Re-run after refreshing the JSON.

Usage (python 2 or 3):
  python scripts/gen_skill_grid_rs.py
"""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
JSON_IN = os.path.join(HERE, "skill_grids.json")
OLD_JSON_IN = os.path.join(HERE, "skill_grids_old.json")
RS_OUT = os.path.join(ROOT, "crates", "wowsunpack", "src", "game_params", "skill_grid_data.rs")

# JSON ship-type key -> Rust Layout field name.
SHIP_FIELDS = [
    ("AIRCARRIER", "air_carrier"),
    ("BATTLESHIP", "battleship"),
    ("CRUISER", "cruiser"),
    ("DESTROYER", "destroyer"),
    ("SUBMARINE", "submarine"),
    ("AUXILIARY", "auxiliary"),
]
GROUP_RS = {"ATTACK": "Attack", "DEFENCE": "Defence", "SUPPORT": "Support", "ACUMEN": "Acumen"}

HEADER = """\
//! GENERATED by scripts/gen_skill_grid_rs.py from scripts/skill_grids.json.
//! Do not edit by hand. Modern (>=0.10) captain skill grid layout, per build
//! threshold and ship species, reverse-engineered from the client's
//! SKILLS_BY_SHIP_TYPE table. Pre-0.10 builds carry tier+column in GameParams
//! instead and are not covered here. Regenerate after adding game versions.
#![allow(dead_code)]

use std::num::NonZeroU32;

use super::types::Species;
use crate::data::Version;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SkillGroup {
    Attack,
    Defence,
    Support,
    Acumen,
}

#[derive(Clone, Copy, Debug)]
pub struct GridSlot {
    /// Skill internal name (matches `CrewSkill::internal_name`).
    pub skill: &'static str,
    /// 0-based tier (row); point cost is `tier + 1`.
    pub tier: u8,
    /// 1-based column within the tier.
    pub column: u8,
    pub group: SkillGroup,
}

struct Layout {
    min_build: NonZeroU32,
    air_carrier: &'static [GridSlot],
    battleship: &'static [GridSlot],
    cruiser: &'static [GridSlot],
    destroyer: &'static [GridSlot],
    submarine: &'static [GridSlot],
    auxiliary: &'static [GridSlot],
}

impl Layout {
    fn species(&self, s: Species) -> &'static [GridSlot] {
        match s {
            Species::AirCarrier => self.air_carrier,
            Species::Battleship => self.battleship,
            Species::Cruiser => self.cruiser,
            Species::Destroyer => self.destroyer,
            Species::Submarine => self.submarine,
            Species::Auxiliary => self.auxiliary,
            _ => &[],
        }
    }
}

/// The captain skill grid for a ship `species` at game `version`, as rows of
/// `GridSlot` ordered by tier then column. Returns the modern per-species layout
/// for >=0.10 versions and the shared pre-rework layout for older ones. `None` when
/// no grid is known: `species` has no captain grid, or `version` predates the
/// oldest extracted layout.
pub fn skill_grid(version: &Version, species: Species) -> Option<&'static [GridSlot]> {
    modern_grid(version, species).or_else(|| old_grid(version))
}

/// Modern (>=0.10) per-species layout. Picks the layout with the largest
/// `min_build <= version.build_number()`; `None` if no layout applies or the
/// species is gridless.
///
/// Gating is by build, not major.minor.patch, because the friendly versions are
/// not monotonic with build: 11.0.0..11.7.0 (builds 5045210..6081105) precede
/// 0.11.8..0.11.11 (builds 6223574..6623042), whose stored version major is 0.
/// `Version::is_at_least` would therefore order 11.0.0 above 0.11.9 and pick the
/// wrong layout. Build precision is required to preserve the threshold ordering.
/// When the build is unknown, fail open to the newest layout.
fn modern_grid(version: &Version, species: Species) -> Option<&'static [GridSlot]> {
    let chosen = match version.build_number() {
        Some(build) => {
            let mut chosen: Option<&Layout> = None;
            for layout in LAYOUTS {
                if layout.min_build.get() <= build {
                    chosen = Some(layout);
                } else {
                    break;
                }
            }
            chosen
        }
        None => LAYOUTS.last(),
    };
    match chosen?.species(species) {
        [] => None,
        slots => Some(slots),
    }
}

/// Pre-rework (<0.10) shared grid from GameParams (tier+column per skill).
/// `group` is unset (Attack) -- pre-rework skills carry no group and the UI
/// orders by tier+column only. Picks the largest `min_build <= build`. `None` if
/// the build predates the oldest layout. Build precision matches `modern_grid`;
/// when the build is unknown, fail open to the newest layout.
fn old_grid(version: &Version) -> Option<&'static [GridSlot]> {
    match version.build_number() {
        Some(build) => {
            let mut chosen: Option<&'static [GridSlot]> = None;
            for (min_build, slots) in OLD_LAYOUTS {
                if min_build.get() <= build {
                    chosen = Some(slots);
                } else {
                    break;
                }
            }
            chosen
        }
        None => OLD_LAYOUTS.last().map(|(_, slots)| *slots),
    }
}

"""


def slot_lit(s):
    # Old (pre-rework) slots carry no group; default to Attack (unused by the UI).
    group = GROUP_RS.get(s.get("group", "ATTACK"), "Attack")
    return '        GridSlot { skill: "%s", tier: %d, column: %d, group: SkillGroup::%s },' % (
        s["skill"],
        s["tier"],
        s["column"],
        group,
    )


def main():
    data = json.load(io.open(JSON_IN, encoding="utf-8"))
    data.sort(key=lambda e: e["min_build"])

    out = io.StringIO()
    out.write(HEADER)
    out.write(u"static LAYOUTS: &[Layout] = &[\n")
    for entry in data:
        out.write(u"    // %s\n" % entry["version"])
        out.write(u"    Layout {\n")
        out.write(u"        min_build: NonZeroU32::new(%d).unwrap(),\n" % entry["min_build"])
        for json_key, field in SHIP_FIELDS:
            slots = entry["grid"].get(json_key, [])
            slots = sorted(slots, key=lambda s: (s["tier"], s["column"]))
            if not slots:
                out.write(u"        %s: &[],\n" % field)
                continue
            out.write(u"        %s: &[\n" % field)
            for s in slots:
                out.write(slot_lit(s) + u"\n")
            out.write(u"        ],\n")
        out.write(u"    },\n")
    out.write(u"];\n")

    # Old (pre-rework) per-build grid (flat, shared across species), deduped.
    out.write(u"\nstatic OLD_LAYOUTS: &[(NonZeroU32, &[GridSlot])] = &[\n")
    if os.path.exists(OLD_JSON_IN):
        old = json.load(io.open(OLD_JSON_IN, encoding="utf-8"))
        last = None
        for v in sorted(old.values(), key=lambda e: e["build"]):
            grid = sorted(v["grid"], key=lambda s: (s["tier"], s["column"]))
            key = json.dumps(grid, sort_keys=True)
            if key == last:
                continue
            last = key
            out.write(u"    // %s\n" % v["version"])
            out.write(u"    (NonZeroU32::new(%d).unwrap(), &[\n" % v["build"])
            for s in grid:
                out.write(slot_lit(s) + u"\n")
            out.write(u"    ]),\n")
    out.write(u"];\n")

    with io.open(RS_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(out.getvalue())
    n_layouts = len(data)
    n_slots = sum(len(v) for e in data for v in e["grid"].values())
    print("wrote %s (%d layouts, %d slots)" % (RS_OUT, n_layouts, n_slots))


if __name__ == "__main__":
    main()
